# Generated by Django 4.2.7 on 2023-11-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('supplier', 'Supplier'), ('salesperson', 'Salesperson')], default='salesperson', max_length=20),
        ),
    ]
