# Generated by Django 4.2.7 on 2023-11-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('opening_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
