# Generated by Django 4.2.7 on 2023-11-04 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_analytics', '0002_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPersonBranch',
            fields=[
                ('salesperson_branch_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_analytics.branch')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_analytics.salesperson')),
            ],
        ),
    ]
