# Generated by Django 4.2.7 on 2023-11-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_analytics', '0003_salespersonbranch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salespersonbranch',
            old_name='created_at',
            new_name='assignment_date',
        ),
    ]
