# Generated by Django 4.2.7 on 2023-11-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_analytics', '0007_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_serialized',
            field=models.BooleanField(default=0),
        ),
    ]
