# Generated by Django 4.2.7 on 2023-11-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_analytics', '0008_set_product_is_serialized_to_false'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('payment_method_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('method_name', models.CharField(max_length=50)),
            ],
        ),
    ]
