# Generated by Django 4.2.7 on 2023-11-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_analytics', '0013_completedsales'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_completed',
            field=models.BooleanField(default=0),
        ),
    ]
