# Generated by Django 4.2.7 on 2023-11-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_analytics', '0015_rename_completedsales_completedsale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sales_person',
            new_name='salesperson',
        ),
    ]
