# Generated by Django 4.2.7 on 2023-11-06 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_analytics', '0016_rename_sales_person_sale_salesperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='amount_currency',
        ),
    ]
