# Generated by Django 4.2.7 on 2023-11-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_analytics', '0017_remove_sale_amount_remove_sale_amount_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='payment_method',
        ),
    ]
